db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: database2:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

spring.profiles.active: qa
logging:
  level:
    root: INFO
    com.dmdev.spring.database.pool: INFO
    org.springframework.jdbc.core: TRACE
  file:
    name: foonk.log
    path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5432/database2
    password: pass
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate





